[package]
name = "vssh"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["process", "fs"] }
anyhow = "1.0"
libc = "0.2"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "vssh"
path = "src/bin/vssh.rs"